### ISSUE TITLE
extention doesn`t work on the new mangadex update 

### ISSUE THREAD

**Issue by KrlSweet** [similar-manga/similar_chrome#1]
i have been refreshing the page for a while even uninstaling the extention and installing again but the extention just doesn`t work anymore for me i thought it might be the new website update since the ui changed a bit so yuo might wanna look into that.

**Comment by goldbattle** [comment]
I pushed an update that should try to more robustly add the button.
You can try loading this repo, or wait for it to be approved on the chrome
extension store.
